version: "3.8"
services:
  shadowing-list-backend:
    container_name: shadowing-list-backend
    restart: on-failure:10
    ports:
      - "8000:8000"
    build: 
      context: ./
      dockerfile: ./shadowing_list/backend/Dockerfile
    volumes:
      - /usr/src/app/node_modules
      - "./shadowing_list/backend/:/usr/src/app/"
    env_file:
      - .env
    depends_on:
      - db
      - prisma
    links: 
      - prisma
    
  prisma:
    image: prismagraphql/prisma:1.34
    container_name: prisma
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: | 
        port: 4466
        databases:
          default:
            connector: postgres
            host: db
            port: 5432
            user: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}
            database: ${POSTGRES_DB}
            migrations: true
    env_file:
      - .env
    links: 
      - db
      
  db:
    build: 
      context: ./shared/database
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./shared/database/db-data:/var/lib/postgresql/data
volumes:
  db-data: