name: Zoop Zoop Frontend CI/CD
on:
    push:
        branches:
            - main

jobs:
    vercel:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  path: apps/shadowing_list/frontend
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14
            - name: deploy to vercel
              run: npx vercel --token ${{ secrets.VERCEL_TOKEN }}
